name: Setup NodeJS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: NodeJS setup
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Check Version
        run: node -v
