name: Setup NodeJS

on:
  push:
    branches:
      - none #main

jobs:
  build:
    name: NodeJS setup
    runs-on: ubuntu-latest

    steps:
      - name: Check Version before installation
        run: node -v

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"

      - name: Check Version
        run: node -v
