name: Build with provenance
on:
  - workflow_dispatch

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: yogeshkumararora/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@v2.0.0
